SELECT C.CAR_ID, 
       C.CAR_TYPE, 
       ROUND(30 * C.DAILY_FEE * (100 - CD.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CD
ON C.CAR_TYPE = CD.CAR_TYPE 
AND CD.DURATION_TYPE = '30일 이상'
WHERE (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
AND NOT EXISTS (
    SELECT 1 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR
    WHERE CR.CAR_ID = C.CAR_ID 
      AND (CR.START_DATE <= '2022-11-30' AND CR.END_DATE >= '2022-11-01')
)
AND ROUND(30 * C.DAILY_FEE * (100 - CD.DISCOUNT_RATE) / 100) >= 500000
AND ROUND(30 * C.DAILY_FEE * (100 - CD.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
